# Generated by Django 4.0.6 on 2022-07-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
