# Generated by Django 4.0.6 on 2022-07-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_comment_comment_body_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='writer',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
